package frc.robot.lib;

/**
 * The following class exists to stop crashes at runtime trying to access missing/mistyped
 * pathweaver files (#145). This class is autogenerated at compile, containing public strings for
 * all of the files in the pathweaver output directory. These public strings are to be used with
 * driveRelativeWaypoints(pathname) in Auto.java instead of directly referring to the pathweaver
 * files.
 */
public class AutoPaths {

    // DO NOT CHANGE THIS FILE!
    // THIS ENTIRE FILE WILL BE REGENERATED BY GRADLE AT COMPILE TIME!
    public static final String kSysid = "sysid.wpilib.json";
    public static final String kTwoPieceBlueA = "twoPieceBlueA.wpilib.json";
    public static final String kTwoPieceBlueB = "twoPieceBlueB.wpilib.json";
    public static final String kTwoPieceBlueC = "twoPieceBlueC.wpilib.json";
    public static final String kTwoPieceRedA = "twoPieceRedA.wpilib.json";
    public static final String kTwoPieceRedB = "twoPieceRedB.wpilib.json";
    public static final String kTwoPieceRedC = "twoPieceRedC.wpilib.json";
    public static final String kScoreMobilityEngageA = "../../pathweaver-slow/output/ScoreMobilityEngageA.wpilib.json";
    public static final String kScoreMobilityEngageB = "../../pathweaver-slow/output/ScoreMobilityEngageB.wpilib.json";

}
