name: Java CI

on:
  push:
    branches: [main]
    paths:
      - "**.java"
      - "**.gradle"
      - "**.json"
      - "**.yml"
  pull_request:
    paths:
      - "**.java"
      - "**.gradle"
      - "**.json"
      - "**.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    # Contains necessary cross-build tools and correct JDK for building applications targeted at the roboRIO
    # https://hub.docker.com/r/wpilib/roborio-cross-ubuntu
    # container: wpilib/roborio-cross-ubuntu:2023-20.04
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Fetch depth 0 will fetch history for all branches and tags
          # This is needed because part of the Gradle build process compares to origin/main
          fetch-depth: 0

      - name: Validate Gradle wrapper
        # Validate checksum of Gradle wrapper JAR
        uses: gradle/wrapper-validation-action@v1

      # Not required if using the roboRIO cross-compile container
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6
          cache-read-only: false

      - name: Compile and test with Gradle
        run: gradle build
